version: "3.7"
services:
  application:
    command: ./start-reload.sh
    environment:
      - ENVIRONMENT=dev
    volumes:
      - ./application/code:/application/code
      - ./application/docs:/application/docs
    build:
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
